# Generated by Django 6.1 on 2026-09-28 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('child_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('health_status', models.TextField(blank=True, null=True)),
                ('education_level', models.CharField(blank=True, max_length=100, null=True)),
                ('is_sponsored', models.BooleanField(default=False)),
                ('is_available_for_adoption', models.BooleanField(default=False)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='children/')),
                ('story', models.TextField(blank=True, null=True)),
                ('needs', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='users.ngo')),
            ],
        ),
    ]
