# Generated by Django 6.1 on 2026-09-28 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('visit_id', models.AutoField(primary_key=True, serialize=False)),
                ('visitor_name', models.CharField(max_length=100)),
                ('visitor_email', models.EmailField(max_length=254)),
                ('visitor_phone', models.CharField(max_length=15)),
                ('visit_date', models.DateField()),
                ('visit_time', models.TimeField()),
                ('purpose', models.CharField(choices=[('volunteer', 'Volunteer'), ('adoption_inquiry', 'Adoption Inquiry'), ('donation_visit', 'Donation Visit'), ('other', 'Other')], max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donations.child')),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ngo')),
            ],
        ),
    ]
